language: ruby
cache: bundler
rvm:
  - 2.4.6
services:
  - mongodb
addons:
  code_climate:
    repo_token: cf3447f19ab3ba56ecc962661bcf070e9b320bc97f9d083ed5720703d1d1083a
after_success:
  - bundle exec codeclimate-test-reporter
