services:
  redis:
    image: redis:6
    ports:
      - 6379:6379
    networks:
      - net
    volumes:
      - redis:/data

  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    networks:
      - net
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

networks:
  net:
    driver: bridge

volumes:
  redis:
  mongodb:
  mongodb_config:
